using Crm.Core.CrmAggregate;
using System.ComponentModel.DataAnnotations;

namespace Crm.Web.ApiModels
{
    // ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
    public class VacancyDTO : CreateVacancyDTO
    {
        public int Id { get; set; }

        public static VacancyDTO FromVacancy(Vacancy vacancy)
        {
            return new VacancyDTO()
            {
                Id = vacancy.Id,
                Title = vacancy.Title,
                Description = vacancy.Description,
                Expired = vacancy.Expired
            };
        }
    }

    // Creation DTOs should not include an ID if the ID will be generated by the back end
    public class CreateVacancyDTO
    {
        [Required]
        public string Title { get; set; }

        public string Description { get; set; }

        public bool Expired { get; set; }
    }
}
